#
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> This comment provides useful information for vibecoding, along with
#     Nakurity Docs Information      debugging hints provided by a linter system in this repository.
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
#
# =======================================================================
#
# Running `pnpm generate-docs` will generate this comment automatically.
# 
# These below will be the information about this file, when this comment
# was generated, etc. This comment is required for linting to pass btw.
#
# =======================================================================
#
# Auto-generated by @nakurity - 15/11/2025 (7:26 PM Sydney Time)
# File Path: /workspace/nakurity-language/workspace/src/core/events.py
# Additional Information: This file should be used everywhere, actually.
#
# Linting: PASSED (Last linted at 15/11/2025 - 7:26 PM)
# Testing: None (No tests registered for this file)
#
# -----------------------------------------------------------------------
# Documentation (None)
# Reason: This file should be pretty self explainatory, actually.
# -----------------------------------------------------------------------
#
from collections import defaultdict
from typing import Callable, Coroutine
from uuid import uuid1
from asyncio import gather

class EventBus:
    def __init__(self):
        # this creates an listener for events, 
        # that both includes non-verified and verified listeners
        self._listeners = defaultdict(list)

        # this is used to optionally verify if the event being listened for, exists or not.
        # verified events are optional, and can be registered by the emitter of that event.
        self._registered_events = list([])

    def on(self, event_name: str, fn: Callable) -> str:
        """Creates an listener for an event with the same name, and pairs with an id.
        That is returned for easy lookups"""

        # generate an id to pair with the listener
        listener_id = uuid1()

        # add the listener function to the list
        # along with its id for easy lookup
        self._listeners[event_name].append({
            "fn": fn,
            "listener_id": listener_id
        })
    
        # Returns the listener id for easy lookups
        return listener_id
    
    def verify(self) -> tuple:
        """Provides a bunch of functions for verification of stuff"""

        def event_exists(event_name: str) -> bool:
            """Verifies if the event exists (i.e. does it have an emitter?)"""
            # Recursively loops thru the registered events
            for event in self._registered_events:
                # If the event is found to be registered (i.e. has an emitter)
                # Then return True.
                if event == event_name: return True

            return False # If the loop above didn't already returned.
            # Then this will run, and return False

        def listener_exists(event_name: str) -> bool:
            """Verifies if there is listeners for a specific event"""
            # If an event name is found to be in the listeners registry
            # return True, because an listener exists.
            if self._listeners[event_name]: return True

            return False # Otherwise, this will run. And return False
        
        return {
            'event_exists': event_exists,
            'listener_exists': listener_exists
        }

    
    def register(self) -> tuple:
        """Provides a bunch of functions for registering stuff"""
        def event(event_name: str):
            """This registers the event as verified it exists"""
            self._registered_events.append(event_name)

        return { # This returns the functions
            'event': event
        }


    def get(self) -> tuple:
        """Provides a bunch of functions to fetch the event listener registry"""
        
        # this function provides utilities that return all listeners, under
        # a specific condition, set by the function
        def all() -> tuple:
            """This function provides an set of functions that get all listeners for a specific condition"""

            # this function gets all listeners, listening for an specific event
            def listener_funcs(event_name) -> list:
                """Get all functions listening for the provided event name"""
                return self._listeners.get(event_name, [])
                # this returns the listeners, listening for the provided event names
            
            return {
                'listener_funcs': listener_funcs
            }
        
        def listener(listener_id: str) -> str | None:
            """Get a listener for an event function, with its specific listener id"""
            async def handle() -> Coroutine | None:
                """An asyncio handle that recursively tries to find the listener
                function, that is paired with the provided event listener id"""

                for event, listeners in self._listeners.items(): # loops thru the listeners registry
                    for listener_obj in listeners:
                        # if an listener's paired id matches the provided one
                        if listener_obj['listener_id'] == listener_id: return listener_obj['fn'] # return the listener function
                
                return None # if no event is found with same id, return None
            
            # Asynchronously run this listener function for performance
            return gather(handle) # and return the result
    
        return {
            'all': all,
            'listener': listener
        }

    def emit(self, event_name: str, **kwargs) -> list:
        """Dispatches an event, and execute it. Then returns the result.
        You can enter the event function's arguments after the event name."""
        return list( # This makes the result expect a list
            # The lamba function runs the fn provided by the event listeners
            map(lambda l: l["fn"](**kwargs), 
                # and this gets the functions for the specific event
                # that was dispatched
                self._listeners.get(event_name, [])
            )) # The map function allows for mapping all of this cleanly to a list
