#!/usr/bin/env node
/**
 * Ultra Nakurity doc header generator:
 * - Supports CLI flags
 * - Supports global + per-file config via .nakurity-docs.json
 * - Falls back to interactive prompts if missing metadata
 */

const fs = require("fs");
const path = require("path");
const readline = require("readline");
const { execSync } = require("child_process");

// -------------------------
// CLI arg parsing
// -------------------------
const args = process.argv.slice(2);
const target = args[0];

function getFlag(name) {
  const prefix = `--${name}=`;
  const match = args.find(a => a.startsWith(prefix));
  return match ? match.replace(prefix, "") : null;
}

// User CLI flags
const cliInfo = getFlag("info");
const cliDocs = getFlag("docs");
const cliReason = getFlag("reason");

// -------------------------
// Config File Handling
// -------------------------
const CONFIG_PATH = path.resolve(".nakurity-docs.json");
let config = {};

if (fs.existsSync(CONFIG_PATH)) {
  config = JSON.parse(fs.readFileSync(CONFIG_PATH, "utf-8"));
}

// Defaults from config
const cfgGlobalInfo = config.defaultInfo ?? null;
const cfgGlobalDocs = config.defaultDocs ?? null;
const cfgGlobalReason = config.defaultReason ?? null;

// File-specific config
function getFileConfig(file) {
  const rel = path.relative(process.cwd(), file).replace(/\\/g, "/");
  return config.files?.[rel] || null;
}

// -------------------------
// Python linter helper
// -------------------------
function runLinter(file) {
  try {
    execSync(`ruff ${file}`, { stdio: "ignore" });
    return "PASSED";
  } catch {
    return "FAILED";
  }
}

// -------------------------
// Interactive prompt helper
// -------------------------
function ask(question) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise(resolve => {
    rl.question(question, ans => {
      rl.close();
      resolve(ans.trim() || null);
    });
  });
}

// -------------------------
// Header builder
// -------------------------
function generateHeader({ filePath, lintStatus, info, docs, reason }) {
  const time = new Date();
  const formatted = time.toLocaleString("en-AU", { timeZone: "Australia/Sydney" });

  let docSection = "";
  if (!docs) {
    docSection = "# Documentation (None)\n# Reason: No reason provided";
  } else {
    const resolved = path.relative(process.cwd(), docs);
    const finalReason = reason || "No reason provided";

    docSection = `# Documentation (${resolved})\n# Reason: ${finalReason}`;
  }

  const extraInfo = info || "None";

  return `#
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> This comment provides useful information for vibecoding, along with
#     Nakurity Docs Information      debugging hints provided by a linter system in this repository.
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
#
# =======================================================================
#
# Running \`pnpm generate-docs\` will generate this comment automatically.
# 
# These below will be the information about this file, when this comment
# was generated, etc. This comment is required for linting to pass btw.
#
# =======================================================================
#
# Auto-generated by @nakurity - ${formatted} Sydney Time
# File Path: ${filePath}
# Additional Information: ${extraInfo}
#
# Linting: ${lintStatus} (Last linted at ${formatted})
# Testing: None (No tests registered for this file)
#
# -----------------------------------------------------------------------
${docSection}
# -----------------------------------------------------------------------
#
`;
}

// -------------------------
// Strip old header
// -------------------------
function stripOldHeader(text) {
  const START = /^# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>/m;
  if (!START.test(text)) return text;

  const lines = text.split("\n");
  let idx = 0;
  while (idx < lines.length && lines[idx].startsWith("#")) idx++;

  return lines.slice(idx).join("\n").trimStart();
}

// -------------------------
// Main
// -------------------------
(async function main() {
  if (!target) {
    console.error("Usage: node tools/generate-docs.js <file.py> [--info=...] [--docs=...] [--reason=...]");
    process.exit(1);
  }

  const abs = path.resolve("..", target);
  const fileCfg = getFileConfig(abs) || {};

  // Priority resolution chain
  let finalInfo =
    cliInfo ??
    fileCfg.info ??
    cfgGlobalInfo ??
    null;

  let finalDocs =
    cliDocs ??
    fileCfg.docs ??
    cfgGlobalDocs ??
    null;

  let finalReason =
    cliReason ??
    fileCfg.reason ??
    cfgGlobalReason ??
    null;

  // If absolutely nothing is provided → ask interactively
  if (!finalInfo && !finalDocs && !finalReason) {
    console.log("No metadata found (CLI, config, defaults).");
    console.log("Please provide minimal information:");

    finalInfo = await ask("Additional Information (or leave blank): ");
    finalDocs = await ask("Documentation file path (or leave blank): ");

    if (finalDocs) {
      finalReason = await ask("Reason (optional): ");
    } else {
      // Reason REQUIRED when no docs
      finalReason = await ask("Reason (required since no docs provided): ");
      if (!finalReason) finalReason = "No reason provided";
    }
  }

  // Safety fallback text
  if (!finalInfo) finalInfo = "None";

  const content = fs.readFileSync(abs, "utf-8");
  const lintStatus = runLinter(abs);
  const cleaned = stripOldHeader(content);

  const header = generateHeader({
    filePath: abs,
    lintStatus,
    info: finalInfo,
    docs: finalDocs,
    reason: finalReason,
  });

  fs.writeFileSync(abs, header + "\n" + cleaned);
  console.log(`✨ Docs generated for ${abs}`);
})();
