#!/usr/bin/env python3
"""
Nakurity Python Linter:
- Parses Nakurity documentation headers
- Validates metadata rules
- Runs backend linter (ruff by default)
- Updates the docblock with new lint results and timestamp
"""

import re
import subprocess
import sys
import os
from datetime import datetime

HEADER_START = r"# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
HEADER_END_SECTION = r"# -----------------------------------------------------------------------"

HEADER_REGEX = re.compile(
    r"# Auto-generated by @nakurity - (?P<timestamp>.+)\n"
    r"# File Path: (?P<path>.+)\n"
    r"# Additional Information: (?P<info>.+)\n"
    r"#\n"
    r"# Linting: (?P<linting>.+?) \(Last linted at (?P<lint_time>.+)\)\n"
    r"# Testing: (?P<testing>.+)\n",
    re.MULTILINE
)

DOC_BLOCK_REGEX = re.compile(
    r"# Documentation \((?P<docs>.*?)\)\n# Reason: (?P<reason>.*)"
)


def run_ruff(file_path: str) -> bool:
    """Run ruff and return True if passed."""
    try:
        subprocess.check_output(["ruff", file_path])
        return True
    except subprocess.CalledProcessError:
        return False


def extract_header(text: str):
    """Extract header block text + content."""
    if HEADER_START not in text:
        return None, text

    lines = text.split("\n")
    header_lines = []
    idx = 0

    # capture header
    while idx < len(lines) and lines[idx].startswith("#"):
        header_lines.append(lines[idx])
        idx += 1

    header_text = "\n".join(header_lines)
    body = "\n".join(lines[idx:]).lstrip("\n")

    return header_text, body


def parse_header(header: str):
    meta = HEADER_REGEX.search(header)
    docs = DOC_BLOCK_REGEX.search(header)

    if not meta:
        raise ValueError("Malformed Nakurity header")

    documentation = docs.group("docs") if docs else "None"
    reason = docs.group("reason") if docs else "No reason provided"

    return {
        "info": meta.group("info"),
        "documentation": documentation,
        "reason": reason
    }


def validate_header(meta):
    """Apply Nakurity metadata rules."""
    docs = meta["documentation"]
    reason = meta["reason"]

    if docs == "None":
        if not reason or reason.strip() == "":
            raise ValueError("Reason required when documentation is None")
    # If docs exists, reason becomes optional


def generate_updated_header(original_header: str, file_path: str, meta, lint_passed: bool):
    """Replace linting status + timestamp inside the original header."""
    now = datetime.now()
    readable = now.strftime("%d/%m/%Y %I:%M %p Australia/Sydney")

    new_lint_line = f"# Linting: {'PASSED' if lint_passed else 'FAILED'} (Last linted at {readable})"

    # Replace the linting line in the block
    new_header = re.sub(
        r"# Linting: .*",
        new_lint_line,
        original_header
    )

    return new_header


def main():
    if len(sys.argv) < 2:
        print("Usage: python nakurity_linter.py <file.py>")
        sys.exit(1)

    file_path = sys.argv[1]

    with open(file_path, "r", encoding="utf8") as f:
        content = f.read()

    header, body = extract_header(content)
    if header is None:
        print("❌ No Nakurity header found.")
        sys.exit(2)

    # Parse metadata
    try:
        meta = parse_header(header)
    except ValueError as e:
        print(f"❌ Header parse error: {e}")
        sys.exit(2)

    # Validate rules
    try:
        validate_header(meta)
    except ValueError as e:
        print(f"❌ Metadata validation failed: {e}")
        sys.exit(3)

    # Run backend linter (ruff)
    lint_passed = run_ruff(file_path)

    # Update header
    updated_header = generate_updated_header(header, file_path, meta, lint_passed)

    # Write back to file
    with open(file_path, "w", encoding="utf8") as f:
        f.write(updated_header + "\n" + body)

    print(f"✨ Linting complete for {file_path}")
    print(f"✨ Status: {'PASSED' if lint_passed else 'FAILED'}")

    sys.exit(0 if lint_passed else 1)


if __name__ == "__main__":
    main()
